// NWS Weather Forecast Office list (CONUS + AK/HI/PR).
// Each entry: 3-letter ID, location name, state.

export interface Wfo { id: string; name: string; state: string; }

export const WFO_LIST: Wfo[] = [
  { id: "ABQ", name: "Albuquerque", state: "NM" },
  { id: "ABR", name: "Aberdeen", state: "SD" },
  { id: "AFC", name: "Anchorage", state: "AK" },
  { id: "AFG", name: "Fairbanks", state: "AK" },
  { id: "AJK", name: "Juneau", state: "AK" },
  { id: "AKQ", name: "Wakefield", state: "VA" },
  { id: "ALY", name: "Albany", state: "NY" },
  { id: "AMA", name: "Amarillo", state: "TX" },
  { id: "APX", name: "Gaylord", state: "MI" },
  { id: "ARX", name: "La Crosse", state: "WI" },
  { id: "BGM", name: "Binghamton", state: "NY" },
  { id: "BIS", name: "Bismarck", state: "ND" },
  { id: "BMX", name: "Birmingham", state: "AL" },
  { id: "BOI", name: "Boise", state: "ID" },
  { id: "BOU", name: "Denver/Boulder", state: "CO" },
  { id: "BOX", name: "Boston/Norton", state: "MA" },
  { id: "BRO", name: "Brownsville", state: "TX" },
  { id: "BTV", name: "Burlington", state: "VT" },
  { id: "BUF", name: "Buffalo", state: "NY" },
  { id: "BYZ", name: "Billings", state: "MT" },
  { id: "CAE", name: "Columbia", state: "SC" },
  { id: "CAR", name: "Caribou", state: "ME" },
  { id: "CHS", name: "Charleston", state: "SC" },
  { id: "CLE", name: "Cleveland", state: "OH" },
  { id: "CRP", name: "Corpus Christi", state: "TX" },
  { id: "CTP", name: "State College", state: "PA" },
  { id: "CYS", name: "Cheyenne", state: "WY" },
  { id: "DDC", name: "Dodge City", state: "KS" },
  { id: "DLH", name: "Duluth", state: "MN" },
  { id: "DMX", name: "Des Moines", state: "IA" },
  { id: "DTX", name: "Detroit/Pontiac", state: "MI" },
  { id: "DVN", name: "Quad Cities", state: "IA" },
  { id: "EAX", name: "Kansas City/Pleasant Hill", state: "MO" },
  { id: "EKA", name: "Eureka", state: "CA" },
  { id: "EPZ", name: "El Paso", state: "TX" },
  { id: "EWX", name: "Austin/San Antonio", state: "TX" },
  { id: "FFC", name: "Atlanta/Peachtree City", state: "GA" },
  { id: "FGF", name: "Grand Forks", state: "ND" },
  { id: "FGZ", name: "Flagstaff", state: "AZ" },
  { id: "FSD", name: "Sioux Falls", state: "SD" },
  { id: "FWD", name: "Dallas/Fort Worth", state: "TX" },
  { id: "GGW", name: "Glasgow", state: "MT" },
  { id: "GID", name: "Hastings", state: "NE" },
  { id: "GJT", name: "Grand Junction", state: "CO" },
  { id: "GLD", name: "Goodland", state: "KS" },
  { id: "GRB", name: "Green Bay", state: "WI" },
  { id: "GRR", name: "Grand Rapids", state: "MI" },
  { id: "GSP", name: "Greenville/Spartanburg", state: "SC" },
  { id: "GUM", name: "Guam", state: "GU" },
  { id: "GYX", name: "Gray", state: "ME" },
  { id: "HFO", name: "Honolulu", state: "HI" },
  { id: "HGX", name: "Houston/Galveston", state: "TX" },
  { id: "HNX", name: "Hanford", state: "CA" },
  { id: "HUN", name: "Huntsville", state: "AL" },
  { id: "ICT", name: "Wichita", state: "KS" },
  { id: "ILM", name: "Wilmington", state: "NC" },
  { id: "ILN", name: "Wilmington", state: "OH" },
  { id: "ILX", name: "Lincoln", state: "IL" },
  { id: "IND", name: "Indianapolis", state: "IN" },
  { id: "IWX", name: "Northern Indiana", state: "IN" },
  { id: "JAN", name: "Jackson", state: "MS" },
  { id: "JAX", name: "Jacksonville", state: "FL" },
  { id: "JKL", name: "Jackson", state: "KY" },
  { id: "KEY", name: "Key West", state: "FL" },
  { id: "LBF", name: "North Platte", state: "NE" },
  { id: "LCH", name: "Lake Charles", state: "LA" },
  { id: "LIX", name: "New Orleans/Baton Rouge", state: "LA" },
  { id: "LKN", name: "Elko", state: "NV" },
  { id: "LMK", name: "Louisville", state: "KY" },
  { id: "LOT", name: "Chicago", state: "IL" },
  { id: "LOX", name: "Los Angeles/Oxnard", state: "CA" },
  { id: "LSX", name: "St. Louis", state: "MO" },
  { id: "LUB", name: "Lubbock", state: "TX" },
  { id: "LWX", name: "Baltimore/Washington", state: "MD" },
  { id: "LZK", name: "Little Rock", state: "AR" },
  { id: "MAF", name: "Midland/Odessa", state: "TX" },
  { id: "MEG", name: "Memphis", state: "TN" },
  { id: "MFL", name: "Miami", state: "FL" },
  { id: "MFR", name: "Medford", state: "OR" },
  { id: "MHX", name: "Newport/Morehead City", state: "NC" },
  { id: "MKX", name: "Milwaukee/Sullivan", state: "WI" },
  { id: "MLB", name: "Melbourne", state: "FL" },
  { id: "MOB", name: "Mobile", state: "AL" },
  { id: "MPX", name: "Twin Cities/Chanhassen", state: "MN" },
  { id: "MQT", name: "Marquette", state: "MI" },
  { id: "MRX", name: "Morristown", state: "TN" },
  { id: "MSO", name: "Missoula", state: "MT" },
  { id: "MTR", name: "San Francisco Bay Area", state: "CA" },
  { id: "OAX", name: "Omaha/Valley", state: "NE" },
  { id: "OHX", name: "Nashville", state: "TN" },
  { id: "OKX", name: "New York City", state: "NY" },
  { id: "OTX", name: "Spokane", state: "WA" },
  { id: "OUN", name: "Norman", state: "OK" },
  { id: "PAH", name: "Paducah", state: "KY" },
  { id: "PBZ", name: "Pittsburgh", state: "PA" },
  { id: "PDT", name: "Pendleton", state: "OR" },
  { id: "PHI", name: "Mount Holly", state: "NJ" },
  { id: "PIH", name: "Pocatello", state: "ID" },
  { id: "PQR", name: "Portland", state: "OR" },
  { id: "PSR", name: "Phoenix", state: "AZ" },
  { id: "PUB", name: "Pueblo", state: "CO" },
  { id: "RAH", name: "Raleigh", state: "NC" },
  { id: "REV", name: "Reno", state: "NV" },
  { id: "RIW", name: "Riverton", state: "WY" },
  { id: "RLX", name: "Charleston", state: "WV" },
  { id: "RNK", name: "Blacksburg", state: "VA" },
  { id: "SEW", name: "Seattle", state: "WA" },
  { id: "SGF", name: "Springfield", state: "MO" },
  { id: "SGX", name: "San Diego", state: "CA" },
  { id: "SHV", name: "Shreveport", state: "LA" },
  { id: "SJT", name: "San Angelo", state: "TX" },
  { id: "SJU", name: "San Juan", state: "PR" },
  { id: "SLC", name: "Salt Lake City", state: "UT" },
  { id: "STO", name: "Sacramento", state: "CA" },
  { id: "TAE", name: "Tallahassee", state: "FL" },
  { id: "TBW", name: "Tampa Bay", state: "FL" },
  { id: "TFX", name: "Great Falls", state: "MT" },
  { id: "TOP", name: "Topeka", state: "KS" },
  { id: "TSA", name: "Tulsa", state: "OK" },
  { id: "TWC", name: "Tucson", state: "AZ" },
  { id: "UNR", name: "Rapid City", state: "SD" },
  { id: "VEF", name: "Las Vegas", state: "NV" },
];
